# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31e8d6cec04535239a9b5de5be1a1b2dd16981ef60fd8ced3971e577a38c95e5ef0c234d9bb01cdba21c5a997044a6759db6af780c6d2122f9c71c3f416e6068

test:
  secret_key_base: d05de5b7d0022b3a3723cea2fba8d0dc5e4cddff4dab167ddeb094ba53583d75ea28aa82c5b823cc20e30c3043c4c9b961959815bfe175ada34a565916ba01a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
